<?php

return [
    'categories' => [
        'Electrónica',
        'Ropa y Moda',
        'Hogar Inteligente',
        'Audio Profesional',
        'Gaming',
        'Deportes',
        'Belleza y Cuidado Personal',
        'Juguetes',
        'Mascotas',
        'Automotriz',
        'Fotografía',
        'Oficina',
        'Salud y Bienestar',
        'Cocina Gourmet',
        'Repostería',
        'Herramientas',
        'Jardinería',
        'Viajes',
        'Libros y Papelería',
        'Video y Streaming',
        'Wearables',
        'Seguridad',
        'Arte y Creatividad',
        'Coleccionables',
        'Car Audio',
        'Accesorios Móviles',
        'Electrodomésticos',
        'Realidad Virtual',
        'Audio para el Hogar',
        'Instrumentos Musicales',
        'Decoración',
        'Papelería Creativa',
        'Kids Tech',
        'Smart Health',
        'Drones',
        'E-sports',
        'Camping y Outdoor',
        'Fitness',
        'Monitores y Proyección',
        'Componentes de PC',
        'Periféricos',
        'Hogar y Limpieza',
        'Reparación y Mantenimiento',
        'Luces Inteligentes',
        'Sostenibilidad',
        'Accesorios Automotrices',
        'Electrónica Naval',
        'Audio para Autos',
        'Streaming Gear',
    ],
    'brands' => [
        'Apple',
        'Samsung',
        'Sony',
        'LG',
        'Microsoft',
        'Google',
        'Nike',
        'Adidas',
        'Puma',
        'Under Armour',
        'Reebok',
        'New Balance',
        'Dell',
        'HP',
        'Lenovo',
        'Xiaomi',
        'Huawei',
        'ASUS',
        'Acer',
        'Philips',
        'Bose',
        'JBL',
        'Panasonic',
        'Canon',
        'Nikon',
        'GoPro',
        'Razer',
        'Logitech',
        'Fender',
        'Yamaha',
        'Bang & Olufsen',
        'Beats',
        'Marshall',
        'Kingston',
        'Corsair',
        'Seagate',
        'Western Digital',
        'ViewSonic',
        'Alienware',
        'MSI',
        'Oculus',
        'Meta',
        'Anker',
        'Belkin',
        'Roku',
        'Philco',
        'Bauknecht',
        'Whirlpool',
        'KitchenAid',
        'Tefal',
        'Rowenta',
        'Patagonia',
        'Columbia',
        'Timberland',
    ],
];
